#pragma once
#define IDI_APPICON                 101
#define IDM_OPEN                    1001
#define IDM_NEXT_IMG                1002
#define IDM_PREV_IMG                1003
#define IDM_ZOOM_IN                 1004
#define IDM_ZOOM_OUT                1005
#define IDM_FIT_TO_WINDOW           1006
#define IDM_FULLSCREEN              1007
#define IDM_DELETE_IMG              1008
#define IDM_EXIT                    1009
#define IDM_ROTATE_CW               1010
#define IDM_ROTATE_CCW              1011
#define IDM_SAVE                    1012
#define IDM_SAVE_AS                 1013
#define IDM_COPY                    1015
#define IDM_PASTE                   1016
#define IDM_OPEN_LOCATION           1017
#define IDM_START_FULLSCREEN        1018
#define IDM_ACTUAL_SIZE             1021
#define IDM_BACKGROUND_GREY         1022
#define IDM_BACKGROUND_BLACK        1023
#define IDM_BACKGROUND_WHITE        1024
#define IDM_BACKGROUND_TRANSPARENT  1025
#define IDM_SINGLE_INSTANCE         1026
#define IDM_PROPERTIES              1027
